### ISSUE TITLE
Invisible blues 

### ISSUE THREAD

**Issue by SirFireNewt** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#1]
I'm unsure if this is an issue with the most recent version or what but the last few times blue phantoms were called on my invasion they were invisible

after some more testing I believe phantoms which are summoned after you're in the hosts world are invisible, saw this happen to a sunbro as an aldrich 

Would it be possible to mark invisible phantoms or to force them to be visible?

**Comment by ReineltS** [comment]
After invading for 3-4 hours at Inner Wall with the Watchdog active yesterday, I can confirm that any players - be it blues, phantoms, or co-invaders - may spawn invisible if they enter the world after you. 
While this happens very rarely in "vanilla" invasions, it's much more prevalent with the tool. 
At least one other player I know estimates it occured about 40% of the time for them, I'd say about half the time in my case. 
One thing I noticed is that it seems to happen much more often when the invaded host was originally alone.

Another glitch that's more common now is not getting sent home when the host enters a bossfight, which I experienced several times with Midir, I made sure to watch until his lifebar and that of the players took damage.
Might be related to the other bug, not sure.

**Comment by SirFireNewt** [comment]
I can confirm that 2nd issue was in the first release and you might want to make another issue for it @ReineltS

**Comment by Jellybaby34** [comment]
Will be looking into it asap. Not sure what could be causing it.

**Comment by Jellybaby34** [comment]
This is fixed in the latest release. Thanks for reporting this.
