### ISSUE TITLE
Virtual levels?

### ISSUE THREAD

**Issue by LeahGoddess** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#10]
Hi, i was just curious if this "mod" accounts for virtual levels that are gained. for example the prisoners chain give you 15 additional levels without raising your sl.

**Comment by LukeYui** [comment]
Yeah it should account for all legit stat boosts such as:

- Knight's/Scholar's/Hunter's/Priest's ring etc.
- Hollow infusions
- Prisoner's Chain
- Other miscellaneous stat boosts.

**Comment by LeahGoddess** [comment]
Thank you! thats a relief because i use some of those items and dont want others using this to flag me for hacking!
