### ISSUE TITLE
Not sure if working or not

### ISSUE THREAD

**Issue by SpiritSushi** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#13]
I don't see the overlay and im not sure if the watchdog is actually working or not.

**Comment by LukeYui** [comment]
If the overlay is not there then it's likely that Watchdog is not active, you can confirm this by making sure the "Start Up Bleep" setting in the .ini file is true and then starting the game.

If there still is no noise when starting the game, it means that Watchdog is not installed correctly. Could you confirm that you extracted the contents of the download (the .ini, .dll etc) in to your DS3 game directory (where DarkSoulsIII.exe is)?

**Comment by SpiritSushi** [comment]
I got it working, i didnt take all the stuff out of the folder, thank you!
