### ISSUE TITLE
User showed as hacker for a split second

### ISSUE THREAD

**Issue by SpiritSushi** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#15]
i was invading and a name went red for a second then went to white, later when i tried to kill the host, he should've died but rolled away with 1 hp

**Comment by shmediaproductions** [comment]
there are lots of cheat engine scripts that only edit memory for a moment. maybe this player's flags tripped the detection and then, upon refresh, no longer tripped the detection. also it's possible he just turned on some stat/attribute hack for a second then turned it off, maybe by mistake.

**Comment by LukeYui** [comment]
Sometimes watchdog might flicker a name red just for a split second if there is quite a lot of latency on the player, just because they haven't quite loaded in yet.

I'm not sure about the 1hp thing, it could have either been really unlucky or they might have been cheating, it's hard to say.

**Comment by turtlshell** [comment]
I had a friend's name flicker red for a split second the other day. He had been in my session for about 15 minutes, he has low latency to me as we live in the same country, and I know for sure that he's not a cheater or anything.

It was kinda weird to see, it didn't say his stats were buffed or anything it just gave me the usual options to kick/ignore etc and turned that whole line red for about a quarter of a second or less.
