### ISSUE TITLE
Fake Alert?

### ISSUE THREAD

**Issue by Tokamak1943** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#18]
I just summon my friend for item-transporting, and I immediately notice that he got labelled as a stats hacker (show:SL120/real:SL802).
We're both really confused because it's clearly impossible for us to do anything that can lead to softbanning.
We suspect that it might be cause by two hackers he met yesterday. Both of them forced buff him with unknown effects.
 Is there any possibility that PVP watchdog can go wrong with this?
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/3387788/DS3PWLog.txt)

**Comment by LukeYui** [comment]
Cheaters can't change your stats. Your friend must have been cheating.

**Comment by Tokamak1943** [comment]
> Cheaters can't change your stats. Your friend must have been cheating.

No, he's not. Definitely not. Not even his stats fit a SL802 character. He hit me like a normal SL120. He die like a normal SL120. He never used any cheats but met cheaters pretty frequently because he's heavy PVP player.

**Comment by LukeYui** [comment]
OK, but cheaters cannot change your stats. The buffs they use on others are temporary and reset after you die or pass through a loading screen.
