### ISSUE TITLE
having ce app on crashes the game

### ISSUE THREAD

**Issue by G3RIVI4N** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#19]
Yes, I know I sound like a retard, but even having CE crashes the game on loading screens. I know watchdog is meant for honest players but not being able to use nodead for longer duel session with your friend without needing to waste time on resummoning because watchdog crashes you kinda sucks. Maybe add a hotkey to turn off watchdog or smth?

**Comment by LukeYui** [comment]
If you want to use cheats, don't use watchdog.

**Comment by G3RIVI4N** [comment]
yeah i expected this answer. Is this an intended mechanic at least?
