### ISSUE TITLE
Phantom can't see invaders

### ISSUE THREAD

**Issue by 0t0k0n0k0** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#2]
Hey guys, was hearing from a guy I was playing dks with that watchdog was working great, I then summoned him so you can pvp against invaders at pontiff. Thing is my he kept telling me he could see the invaders. He tried restarting his pc but that didn't work, he then uninstalled watchdog and the game started working fine for him. I know this is a similar issue with the "Invisible blues" post, but i thought it was worth mentioning since it was summon in my world that couldn't see.

**Comment by Scaryowl** [comment]
Hi, i'm the guy that had the issues. Should specify that I could see reds when invading, but otherwise they were invisible.

Also, the problem wasn't immediate, and at first was able to be fixed by restarting the game.

**Comment by Jellybaby34** [comment]
This is fixed in the latest release. Thanks for reporting this.
