### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AVDaniel** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#20]
[LOGSTR 11:00:42] Launching Dark Souls III...
[LOGSTR 11:00:42] Update Check
[LOGSTR 11:00:42] End Update Check
[LOGSTR 11:01:10] SaveFolderID: 0110000135ab1d90, Savefolder path: C:\Users\Daniel\AppData\Roaming\DarkSoulsIII\0110000135ab1d90
[LOGSTR 11:02:48] Launching Dark Souls III...
[LOGSTR 11:02:49] Update Check
[LOGSTR 11:02:49] End Update Check
[LOGSTR 11:03:18] SaveFolderID: 0110000135ab1d90, Savefolder path: C:\Users\Daniel\AppData\Roaming\DarkSoulsIII\0110000135ab1d90
[LOGSTR 11:15:41] Leaving Session...
[LOGERR 11:16:16] Rendering stack leak
[LOGERR 11:16:17] Unable to shade polygon normals. Error Code: 6561198860672400 
Inform /u/TheSpicyChef and send your log file.
[LOGSTR 11:31:56] Launching Dark Souls III...
[LOGSTR 11:31:56] Update Check
[LOGSTR 11:31:56] End Update Check
[LOGSTR 11:32:22] SaveFolderID: 0110000135ab1d90, Savefolder path: C:\Users\Daniel\AppData\Roaming\DarkSoulsIII\0110000135ab1d90
[LOGERR 11:33:28] Rendering stack leak
[LOGERR 11:34:36] Unable to shade polygon normals. Error Code: 6561198860672400 
Inform /u/TheSpicyChef and send your log file.

**Comment by Nyleen** [comment]
[LOGSTR 23:54:37] Launching Dark Souls III...
[LOGERR 23:55:20] Rendering stack error: B28C9E5F
[LOGERR 23:56:39] Rendering stack error: B28C9E5F
[LOGERR 23:57:23] Unable to shade polygon normals. Error Code: 6561198263029520 
Inform /u/TheSpicyChef and send your log file.

I am getting a similar error. :C

**Comment by Jellybaby34** [comment]
This should be fixed in the most recent build.
