### ISSUE TITLE
Whitescreen Crash after invading. Posting here incase its helpful

### ISSUE THREAD

**Issue by SkysAreRed** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#22]
Invaded people, game screen went white and had to restart dark souls due to it freezing up. The data got saved in the ds3log that is included. Do i post the information here from the log or can I PM it to you.

:)

**Comment by LukeYui** [comment]
Hello, sorry for the delay in responding. Yes, please post the log here and we can look through it and try to identify the issue.

**Comment by Jellybaby34** [comment]
If this issue is still present, make another issue. I'm closing this old one
