### ISSUE TITLE
"Unable to shade polygon normals"

### ISSUE THREAD

**Issue by fluxxio** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#24]
I don't know if this is a meme error, but I've been unable to use watchdog at all. I'm not using a modified save, don't have CE open, no mods, even reinstalled and cleared my save directory because I heard someone in TGA discord a while ago say watchdog auto shuts down if it detects anything CE related. What exactly is going on here?

**Comment by LukeYui** [comment]
Hello, sorry to hear this; Please post your log file (DS3PWLog.txt) here so that we can identify and clarify the issue for you. Thanks

**Comment by fluxxio** [comment]
Sure. Sorry for the late reply, but here you go. 

[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/3856404/DS3PWLog.txt)

**Comment by turtlshell** [comment]
[I had the same issue](https://ghostbin.co/paste/434x2) on alt+tab

**Comment by oloier** [comment]
Also having this problem, does seem to occur with alt+tab

**Comment by Jellybaby34** [comment]
Try the 1.0.10 beta
https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/tree/beta

If this is still an issue, open another report
