### ISSUE TITLE
Watchdog Crash Log: Access Violation

### ISSUE THREAD

**Issue by turtlshell** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#25]
Seemed to happen randomly during a pretty full online session. [DS3PWLog.txt](https://ghostbin.co/paste/oyf56)

[My DS3PWSettings.ini file](https://ghostbin.co/paste/7rq5t)

**Comment by LukeYui** [comment]
Hello, thanks for the report and the log; I've identified the problem and corrected it - It will be fixed in the next version.

**Comment by turtlshell** [comment]
A few more similar looking but slightly variant crash log dumps [here](https://ghostbin.co/paste/e6pot)

**Comment by turtlshell** [comment]
[One more](https://ghostbin.co/paste/upxdn) because I've crashed quite a lot today

**Comment by LukeYui** [comment]
Thanks for the further information -- These all seem to be the same crash or variances of the same crash. The problem should be fixed now, and we'll aim to push out a fix for it early next week.
