### ISSUE TITLE
Feature Request - Whitelist Players/Temporarily Disable Anti-cheat

### ISSUE THREAD

**Issue by RebornFX** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#26]
Love this mod for playing against randoms, but I often duel with friends who use cheat engine to heal us both after each duel so we don't need to constantly resummon each other every time we run out of estus and the mod doesn't allow this. This is a pretty common thing for duelists to do.

Would it be possible to add the ability to whitelist certain players that you know aren't using cheat engine maliciously, or add a hotkey that temporarily disables the anti-cheat preventing effects being applied to your character, but still keeps the features of showing who is in the world, highlighting cheaters etc? Right now if I'm not mistaken I would have to uninstall the mod each time I want to play with my friends and reinstall when I'm done, which I'd rather not do. If I'm being honest I mostly use the mod for identifying the steam names of insanely laggy players so I can block them, I'm not really so concerned about cheaters since they're often pretty easy to identify and I keep plenty of save backups.

**Comment by turtlshell** [comment]
Idk about using cheats to heal is a "pretty common thing" most players choose to not cheat and just resummon when they run out of estus

**Comment by RebornFX** [comment]
> Idk if using cheats to heal is a "pretty common thing" most players choose to not cheat and just resummon when they run out of estus

I never said most players do it, I said it's common, especially amongst the tryhard dueling community.   It's also used in tournaments after a latency test. It doesn't give anybody any unfair advantage, just saves time waiting through load screens.

**Comment by turtlshell** [comment]
Dunno about that, fine line, essentially asking to be able to cheat when it benefits you but stop other people from cheating at the same time. Just my 2c, dev's decision lol

**Comment by LukeYui** [comment]
Hi, the purpose of Watchdog is to be a tool to protect your game against cheaters, not just an all-purpose PvP tool. For this reason I wouldn't be comfortable making changes to let _some_ things through, while blocking other things for certain people.

If you want to play with your friends who are going to be using cheats on you, and you want them to, you could close the game and rename the "d3d11.dll" to something like "d3d11B.dll" which would disable the mod, then reverse the change when you're back playing with randoms.

**Comment by uselessknickknacks** [comment]
Working on a simple java application that will allow you to pick if you want to launch DS3 with WatchDog or Not. Using that core principle of renaming the d3d11.dll

If anything it saves people time. 

It will also watch the DS3 process after you have launched it. And when DS3 closes (or crashes or whatever), it will rename the file back to normal again. So you will never have to bother with opening the folder and renaming and all that jazz back and forth. This program will automate that task for you.

It also contains a extra step by checking if the file really is named d3d11.dll if you press the "Launch with PVP WatchDog", which is there in case a user case scenario I cannot predict (for example the user changing the file name themselves) occurs. In which case it will also rename it back to d3d11.dll.

No it will not be able to do anything fancy or modify PVP WatchDog in any way. It's more like a fun little exercise for me in interacting with processes (aka reading the processor list), timers and file reading.

I will post a link to it here along with source code when I am done.
