### ISSUE TITLE
Game crashing and occasional shade polygons error. Log Below.

### ISSUE THREAD

**Issue by zetsuya** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#27]
I hope I can be of any help to fix these issues.

[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/3877090/DS3PWLog.txt)

**Comment by turtlshell** [comment]
polygons error is a dupe of #24 but the other access violation crash isn't

**Comment by LukeYui** [comment]
Hello, thanks for the report. The access violation crash is the same as #25 and has been fixed, it'll be patched in the next update.

**Comment by zetsuya** [comment]
> Hello, thanks for the report. The access violation crash is the same as #25 and has been fixed, it'll be patched in the next update.

About shade polygons, I've stopped receiving them after I stopped using MSI Afterburner, it it helps in any way.

**Comment by turtlshell** [comment]
I've had the unable to shade polygons error with and without a GPU overclock, and since I'm on Linux I don't use MSI Afterburner so I doubt that's the issue.
That issue happens really sporadically for me so you might have just gotten lucky or something, not sure.
