### ISSUE TITLE
Watchdog randomly kicking people in duels

### ISSUE THREAD

**Issue by bassclarinet69** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#28]
Weren't flagged, autokick was off. Matched with the same person three times after they had been kicked once and had no issues. Never had it happen with 1.0.5. Log from a fresh install this morning with wex dust, was happening without too. Kicks right after both players load in. I had this happen repeatedly when trying to update from 1.0.5 before. Apologies for not posting about it sooner.
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/3882761/DS3PWLog.txt)

**Comment by LukeYui** [comment]
Sorry for the delay in responding. This issue has been addressed in new versions of the mod.
