### ISSUE TITLE
Game crashes randomly.

### ISSUE THREAD

**Issue by BadFoxDragon** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#29]
I'm sure it's somehow my fault, I am also using Wex Dust mod cause it's so friggin handy.

[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/3907867/DS3PWLog.txt)

**Comment by LukeYui** [comment]
Hello, sorry for the late response. Thanks for the report, the issue has been fixed and the next version will be released when we're absolutely sure there is no risk of ban from the update.

**Comment by RunnyEggYolk** [comment]
Is there any update on this issue?  I am experiencing the same Watchdog crash.  I am also using Wex Dust and I have RivaTunerStatisticsServer running to monitor GPU temperature.

**Comment by UkrainianCitizen** [comment]
> I tend to crash as well during lengthy pvp sessions(typically when I invade) and typically several phantoms are involved. Happened at least 3 times during 2 days. The errors in the logs are identical to yours.

[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/4397707/DS3PWLog.txt)

**Comment by UkrainianCitizen** [comment]
> I tend to crash as well during lengthy pvp sessions(typically when I invade) and typically several phantoms are involved. Happened at least 3 times during 2 days. The errors in the logs are identical to yours.

[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/4397712/DS3PWLog.txt)

**Comment by UkrainianCitizen** [comment]
@LukeYui Consider closing related duplicate #32.

**Comment by LukeYui** [comment]
@Jellybaby34 I can't close issues on this Git page.

**Comment by UkrainianCitizen** [comment]
@LukeYui I see, I thought you are contributor, maybe a repository owner can include you in contributors, this way you'll be able to close issues.

**Comment by Jellybaby34** [comment]
Try the 1.0.10 beta
https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/tree/beta

If this is still an issue, open another report
