### ISSUE TITLE
Boss does not send invader (you) home

### ISSUE THREAD

**Issue by SirFireNewt** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#3]
This was an issue in 1.0 too.

When a host walks into the boss fight you simply don't get sent home as an invader and have to black crystal out

_(referenced in #1 made it's own issue for organization)_

**Comment by Jellybaby34** [comment]
This is fixed in the next update, we're going to push it along with the invisible phantom fix in the next couple of days. Thanks for reporting this!
