### ISSUE TITLE
Unable to shade polygon normals.

### ISSUE THREAD

**Issue by Cyber-XxXx** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#30]
Hello,
Sorry im very new to this whole "mod" but i've tried to search for solutions but haven't found any.
Im getting the error "Unable to shade polygon normals." pretty much after launching DS3.
I've tried disabling MSI Afterburner, but that didn't help either. (Also deleted all the Mod files, re-downloaded & added them again etc.)

Is there something i've missed or got patched? 
Im using version 1.0.6
Attached is Log File.

[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/4072877/DS3PWLog.txt)

**Comment by Satheus** [comment]
I've experienced this issue as well. It turned out to be RivaTuner Statistic Server, even with it being turned off for DS3 and globally.

**Comment by Cyber-XxXx** [comment]
> [DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/4138500/DS3PWLog.txt)
> I've experienced this issue as well. It turned out to be RivaTuner Statistic Server, even with it being turned off for DS3 and globally. Whenever the game would lose focus the error would pop up eventually when the game refocused.

Thank you!!!
