### ISSUE TITLE
Game Crashes randomly from invasions. Only have Wex Dust mod installed.

### ISSUE THREAD

**Issue by SirRonan** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#31]
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/4075029/DS3PWLog.txt)

**Comment by LukeYui** [comment]
Hello, thanks for the report. This issue has been fixed, and it the updated version will be released when we are absolutely certain there is no risk of ban with the update.

**Comment by SirRonan** [comment]
Thank you! Will be looking forward to the next release. :)
