### ISSUE TITLE
Clicking off screen causes a crash

### ISSUE THREAD

**Issue by GrandVizierNappa** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#33]
When clicking on another monitor or screen with google or any other program the game will say as long as pvp watchdog is active unable to shade polygons as well as crash the game sometimes it is very repeatable. error 6561199014747092

**Comment by GrandVizierNappa** [comment]
turns out if you have any form cheat engine scripts running in the background regardless if you use them or not the watchdog does not work

**Comment by LukeYui** [comment]
Hi, cheat engine is completely incompatible with watchdog.

**Comment by Jellybaby34** [comment]
Fixed in 1.0.10 beta 
https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/tree/beta
