### ISSUE TITLE
Watchdog silently crashing but keeping in-game overlay

### ISSUE THREAD

**Issue by RunnyEggYolk** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#35]
I just had a session where the Watchdog in-game overlay was visible and being updated (the clock was running), but Watchdog did not give me any information about other players during that session.  I was summoned into another world as a phantom, and that world had invaders in it, and I didn't see any Watchdog info about either the host or the invaders.  Later, I was invaded in my own world, and I didn't get any info about the invaders.  After ending the session, I looked in DS3PWLog and today's session literally only has this in it:

```
[LOGSTR 12:35:21] Launching Dark Souls III...  
[LOGSTR 12:35:21] Fetching data file...  
[LOGSTR 12:35:21] Update Check  
[LOGSTR 12:35:21] End Update Check  
[LOGSTR 12:35:21] Storing data file  
[LOGSTR 12:35:21] Storing data file  
[LOGSTR 12:35:21] Opening data file  
[LOGERR 12:35:21] Failed to parse data file  
[LOGSTR 12:35:21] Finished fetching data file  
[LOGSTR 12:35:34] SaveFolderID: <my steam ID number>, Savefolder path: <the correct path to my DS3 saves>
```

There was nothing else in the log after the `SaveFolderID` line.

That `Failed to parse data file` looks ominous.

**Comment by outryder** [comment]
Never happened anything like that.

Also, to devs: hardware/software configs would at least could give some idea about issue circumstances. (As in my experience, v.1.0.6 didn't work properly in Win7)

**Comment by LukeYui** [comment]
I've also noticed that watchdog has issues in windows 7 (as do most of my other mods). I'm completely unsure why, this could be what is causing the bugs I cannot recreate in-game myself.

**Comment by RunnyEggYolk** [comment]
FWIW I'm running Windows 10 build 1903, and I've gotten this exact same behavior many times since I first posted this bug.

**Comment by outryder** [comment]
Yes, also using 1903 at the moment, though never encountered such behavior.
(1909 same)

сб, 28 мар. 2020 г. в 22:56, RunnyEggYolk <notifications@github.com>:
