### ISSUE TITLE
Watchdog interfering with Aldrich Faithful? (Edit)

### ISSUE THREAD

**Issue by LondorPaleShade** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#36]
I've been doing a couple of Aldrich Faithful invasions after getting the Watchdog and I've had three connection errors upon the host's death in a row, preventing me from getting the reward. Could the program be interfering with covenant items somehow?

(Edit)
As it turns out, Watchdog is interfering with ALL of the things that should happen upon a host's death. I'm tempted to uninstall and reinstall both Watchdog and DS3 to see whether that helps, but for now I'm just going to have to suck it up

**Comment by SirFireNewt** [comment]
That's very odd, I run both watchdog and wex dust, but don't have that issue

**Comment by LukeYui** [comment]
This is a bug I unfortunately cannot re-create in-game. I understand a few people have this issue but it works fine for others. Can I ask what operating system you're running?

**Comment by LondorPaleShade** [comment]
Still running Windows 7

**Comment by LukeYui** [comment]
Hello, sorry for the delay in responding. The issue has been identified and fixed. As soon as the new version has been proven safe the beta branch will be updated. Thanks again
