### ISSUE TITLE
I am on the latest version but I am getting notified about a new version

### ISSUE THREAD

**Issue by UkrainianCitizen** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#39]
I am on the latest 1.0.7 version but when I start DS 3 I am getting notification window about a new version and the in-game mod status line also tells this:
![20200328153212_1](https://user-images.githubusercontent.com/31314423/77824223-d2975980-7109-11ea-8838-bfeab8ec914c.jpg)

**Comment by LukeYui** [comment]
Hi, this will just be like this while 1.0.7 is in beta, the full version should be out soon and this won't happen anymore.
