### ISSUE TITLE
When using watchdogs, Player models "remain" at the edge of moveables

### ISSUE THREAD

**Issue by CodeMonkeyGamal** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#42]
When the player model gets to an elevator (anywhere in the game), or, for example a moveable bridge in cathedral, the player model "sticks" in place on the other players screen (but on the character that's moving you're in the correct place). Only upon leaving the moveable, does the model snap to the "correct" position. 

This is also not simple a graphical glitch: because the model is where it is on screen, an invader can hit the model. (it's also able to block players).

The damage is transferred to the player in the correct place.

We tested backstabs, seems these are not possible though.

Tested with and without watchdogs 1.08
Does not happen with watchdogs uninstalled.

**Comment by LukeYui** [comment]
Hello, thanks for the report. This issue was flagged up on NexusMods, and it has been fixed ready for the next version. Once the next version is proven save, the beta will be up ASAP.

**Comment by Jellybaby34** [comment]
Fixed in 1.0.10 beta
https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/tree/beta
