### ISSUE TITLE
Sacred Flame don't work

### ISSUE THREAD

**Issue by ArduinoHittme** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#43]
Hi, PvP Watchdog affect the sacred flame grab for some reason. Even though the enemy have the animation, I don't have it, and the enemy don't take any damage from the grab, which makes this spell even more useless.
The spell work as intended when pvp watchdog is unistalled.

**Comment by LukeYui** [comment]
Hi, thanks for the report.

Sacred flame and the dark hand grab have had issues for a while now, I'm looking into fixing them for future versions.

**Comment by LukeYui** [comment]
Fixed, thanks again for the report.
