### ISSUE TITLE
 Watchdog failed to parse data file  

### ISSUE THREAD

**Issue by zergvszerg** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#45]
After a fresh install, the mod kept preventing me from entering any pvp session, and the log says it failed to parse data file.
I've got no choice but to uninstall watchdog, after uninstallation I get non stop invasions right away.

**Comment by Jellybaby34** [comment]
Fixed in 1.0.10 beta
https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/tree/beta
