### ISSUE TITLE
Items visually flooding the screen

### ISSUE THREAD

**Issue by FrazzoJustACoder** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#46]
![image](https://user-images.githubusercontent.com/20447641/80730217-9771b700-8b09-11ea-80a3-e7fcbc8da345.png)
Well I was playing alone and as soon as I locked a mob, "that" appeared, then i unlocked it and it disappered. Then I did the same and it appeared again. Then i went to the bonefire and it never happened again. I can't manage to replicate it. Log file doesn't contain anything different from usual
(version 1.0.8)

**Comment by LukeYui** [comment]
Hello, thanks for the report. This is a well known bug with the base game, and isn't caused by watchdog. 

See here: https://www.reddit.com/r/darksouls3/comments/4phn0h/what_is_this_glitch_huge_overlay_on_screen/
