### ISSUE TITLE
Crashing when invading/summoning

### ISSUE THREAD

**Issue by Baiize** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#5]
So I recently downloaded and placed the files in the correct folder, the game runs fine. I see the info bar on the top left as intended.
When I invade or try to summon it locks my game out and crashes it. Here are the logs fromDS3PW.

[LOGSTR 22:32:26] Launching Dark Souls III...
[LOGSTR 22:32:26] Update Check
[LOGSTR 22:32:26] End Update Check
[LOGSTR 22:32:44] SaveFolderID: 01100001058a0585, Savefolder path: C:\Users\Dave\AppData\Roaming\DarkSoulsIII\01100001058a0585
[LOGSTR 22:42:05] Unable to shade polygon normals. Error Code: 6561198053197189
Inform /u/TheSpicyChef

I have since moved my install folder from my D to my C drive and replaced the files from Github as opposed to the original I got form nexusmods.

Not sure exactly what happened, but it now works as intended. Just wanted to flag this for any future people who may come across the same problem.

**Comment by Jellybaby34** [comment]
Check if this is still an issue in the current release and post your log if it is.
