### ISSUE TITLE
Sacred  flame does nothing

### ISSUE THREAD

**Issue by NunoJDCM** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#50]
I'm not sure if you're using sacred flame as a mechanism to kick, but every time I use sacred flame as a host, the player hit gets kicked, and if I'm not the host, nothing happens, the target just gets staggered

**Comment by LukeYui** [comment]
Hi, thanks for the report. This is a known issue with 1.0.10, it has been identified and fixed, and will be patched in the next version.
