### ISSUE TITLE
[1.0.10] Legitimate weapon buffs don't apply status ailments

### ISSUE THREAD

**Issue by Eroc** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#51]
Status-inducing buffs like Frozen Weapon or Rotten Pine Resin seem to be falsely detected and blocked as malicious effects with Watchdog 1.0.10. There's no buildup applied whatsoever when you get hit by them.

**Comment by LukeYui** [comment]
Hi, thanks for the report. This has been identified and fixed, and will be patched with the next version.
