### ISSUE TITLE
More verbose log - request

### ISSUE THREAD

**Issue by Lignar** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#52]
Hello, would it be possible to make an entry in DS3PWLog.txt at the moment when cheater gets detected? I'm thinking about writing to the log pretty much the same line that is displayed in the overlay.

**Comment by LukeYui** [comment]
Hi, sorry for the delay. This is something we've been working on, and the rewritten version of the mod (which should be out soon) does this in much more detail which should make knowing exactly why a cheater got flagged a lot more obvious.
