### ISSUE TITLE
Watchdog suddenly crashes

### ISSUE THREAD

**Issue by DesgraciadoParia** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#6]
I recently updated to the 1.0.3 version, and the software suddenly crashed, the game continued just fine though. Here's the log:

[LOGSTR 16:32:59] Launching Dark Souls III...
[LOGSTR 16:32:59] Update Check
[LOGSTR 16:32:59] End Update Check
[LOGSTR 16:33:20] SaveFolderID: 011000010547329e, Savefolder path: C:\Users\Carlos\AppData\Roaming\DarkSoulsIII\011000010547329e
[LOGERR 16:33:47] Rendering stack error: 571581E7
[LOGERR 16:34:58] Rendering stack error: 571581E7
[LOGERR 16:35:55] Unable to shade polygon normals. Error Code: 6561198048817822 
Inform /u/TheSpicyChef and send your log file.

Also.... sometimes the game doesn't start, it's not a big problem, if I try to start the game again it works, but it's a bit annoying, it has happened with all the watchdog versions and it didn't happen before.

**Comment by Jellybaby34** [comment]
Should be fixed in the new release
