### ISSUE TITLE
Whenever i use F1 to kick a cheater (false stats or otherwise) it simply crashes my game

### ISSUE THREAD

**Issue by CutleryMan** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#65]

**Comment by RedPlumpTomato** [comment]
I'm having the same issue. Hacker comes into my world, I press F1 and the game crashes back to my desktop.

**Comment by LukeYui** [comment]
Hi, sorry for the delay. This is fixed in the beta version (1.0.11) of the mod, I recommend you use this instead.

**Comment by RedPlumpTomato** [comment]
Awesome.  Thanks.

________________________________
