### ISSUE TITLE
App crash (cheats/hacks)

### ISSUE THREAD

**Issue by outryder** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#66]
Player had a Family share, and his behavior looked strange. Some time after app crashed.

[LOGSTR 23:02:16] Player: Keith!?, SteamID: 0110000141AF8E7E is using a family shared account. Main SteamID: 0110000135F404E0
[LOGSTR 23:21:58] Player: Keith!?, SteamID: 0110000141AF8E7E is using a family shared account. Main SteamID: 0110000135F404E0
[LOGERR 23:28:31] ----- [YuiSpy Activated] -----
[LOGERR 23:28:31] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 23:28:31] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 23:28:31] Exception Flags: 0
[LOGERR 23:28:31] Exception Flags: 0
[LOGERR 23:28:31] Fault Offset: 0x140F06C82
[LOGERR 23:28:31] Fault Offset: 0x140F06C82
[LOGERR 23:28:31] Number Parameters: 2
[LOGERR 23:28:31] Number Parameters: 2
[LOGERR 23:28:31] The instruction at 0x140F06C82 referenced memory at 0x0. The memory could not be written.
[LOGERR 23:28:31] The instruction at 0x140F06C82 referenced memory at 0x0. The memory could not be written.
[LOGERR 23:28:31] Dumping session information:
[LOGERR 23:28:31] Dumping session information:
[LOGERR 23:28:31] Generating register dump:
[LOGERR 23:28:31] RAX: 0x0
[LOGERR 23:28:31] RAX: 0x0
[LOGERR 23:28:31] RBX: 0x144917630
[LOGERR 23:28:31] RBX: 0x144643A58
[LOGERR 23:28:31] RCX: 0x7
[LOGERR 23:28:31] RCX: 0x7
[LOGERR 23:28:31] RDX: 0xADD340B9
[LOGERR 23:28:31] RDX: 0xADD340B9
[LOGERR 23:28:31] RDI: 0x0
41A594710
[LOGERR 23:28:31] RSI: 0xE1689358
[LOGERR 23:28:31] RSI: 0x653FE70
[LOGERR 23:28:31] R8:  0x0
[LOGERR 23:28:31] R8:  0x142757068
[LOGERR 23:28:31] R9:  0x1
[LOGERR 23:28:31] R9:  0x40
[LOGERR 23:28:31] R10: 0x8000
[LOGERR 23:28:31] R10: 0x400
[LOGERR 23:28:31] R11: 0x9DFFBB0
[LOGERR 23:28:31] R11: 0x3DF5FB20
[LOGERR 23:28:31] R12: 0x7FF41B5916F0
[LOGERR 23:28:31] R12: 0x0
[LOGERR 23:28:31] R13: 0x7FF41B591728
[LOGERR 23:28:31] R13: 0x1
[LOGERR 23:28:31] R14: 0x0
[LOGERR 23:28:31] R14: 0x7FF41A594760
[LOGERR 23:28:31] R15: 0x0
[LOGERR 23:28:31] R15: 0x7FF41A5947A0
[LOGERR 23:28:31] RBP: 0x0
[LOGERR 23:28:31] RBP: 0x3DF5FCD0
[LOGERR 23:28:31] RSP: 0x9DFFC98
[LOGERR 23:28:31] RSP: 0x3DF5FC18
[LOGERR 23:28:31] ------ [YuiSpy Complete] -----
[LOGERR 23:28:31] ------ [YuiSpy Complete] -----

First time he was in a session. Second time he was alone. Probably he couldn't bear a defeat?

**Comment by outryder** [comment]
Another one. A cheat/hack use for sure. Crashed game at the start of invasion.
[LOGERR 13:27:52] ----- [YuiSpy Activated] -----
[LOGERR 13:27:52] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 13:27:52] Exception Flags: 0
[LOGERR 13:27:52] Fault Offset: 0x7FF9B9A14B77
[LOGERR 13:27:52] Number Parameters: 2
[LOGERR 13:27:52] d3d11.dll+14B77
[LOGERR 13:27:52] The instruction at 0x7FF9B9A14B77 referenced memory at 0x80. The memory could not be read.
[LOGERR 13:27:52] Dumping session information:
[LOGERR 13:27:52] Player Slot: 1, My account
[LOGERR 13:27:52] Player Slot: 2, Name: new, Steam ID: 0110000103101E3E, Owner Steam ID: 0110000103101E3E
[LOGERR 13:27:52] Generating register dump:
[LOGERR 13:27:52] RAX: 0x0
[LOGERR 13:27:52] RBX: 0x0
[LOGERR 13:27:52] RCX: 0x7FF9B9A46FC0
[LOGERR 13:27:52] RDX: 0x0
[LOGERR 13:27:52] RDI: 0x7FF9B9A46CE0
[LOGERR 13:27:52] RSI: 0x7FF9B9A46DC0
[LOGERR 13:27:52] R8:  0x7FF49E897E10
[LOGERR 13:27:52] R9:  0x1
[LOGERR 13:27:52] R10: 0x8000
[LOGERR 13:27:52] R11: 0x75EF6E0
[LOGERR 13:27:52] R12: 0x2
[LOGERR 13:27:52] R13: 0x2
[LOGERR 13:27:52] R14: 0x2
[LOGERR 13:27:52] R15: 0x4
[LOGERR 13:27:52] RBP: 0x75EF7F0
[LOGERR 13:27:52] RSP: 0x75EF6F0
[LOGERR 13:27:52] ------ [YuiSpy Complete] -----

Though steam showed 5/6 other accounts. So that probably was a host summoning to crash or else.

**Comment by outryder** [comment]
Posting, for it might be of use for development.
Thanks for the program! Without it, the only other possible way to play this game is CE (with custom setup protection, which I don't have).

**Comment by LukeYui** [comment]
Thanks for the post. We've identified and fixed both crashes and they should be ready for the next update.

**Comment by outryder** [comment]
Thanks!

**Comment by outryder** [comment]
There are some more instances of DS3(+Watchdog?) crashes. I will post them here now, and if you still need such crash log data, let me know.

**Comment by outryder** [comment]
Player had infinite poise, really impossible for his setup (double checked that). And he was acting too confident (for a complete scrub ;-) ). Just few seconds, after he died, my game crashed.

[LOGERR 22:17:39] ----- [YuiSpy Activated] -----
[LOGERR 22:17:39] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 22:17:39] Exception Flags: 0
[LOGERR 22:17:39] Fault Offset: 0x14082BAA9
[LOGERR 22:17:39] Number Parameters: 2
[LOGERR 22:17:39] The instruction at 0x14082BAA9 referenced memory at 0x0. The memory could not be written.
[LOGERR 22:17:39] Dumping session information:
[LOGERR 22:17:39] Generating register dump:
[LOGERR 22:17:39] RAX: 0x1
[LOGERR 22:17:39] RBX: 0x0
[LOGERR 22:17:39] RCX: 0x0
[LOGERR 22:17:39] RDX: 0x1
[LOGERR 22:17:39] RDI: 0xFFFFFFFFFE5384A6
[LOGERR 22:17:39] RSI: 0x0
[LOGERR 22:17:39] R8:  0x1469FB68
[LOGERR 22:17:39] R9:  0x1469FD10
[LOGERR 22:17:39] R10: 0x0
[LOGERR 22:17:39] R11: 0x246
[LOGERR 22:17:39] R12: 0x3F800000
[LOGERR 22:17:39] R13: 0x7FF4FCC14D30
[LOGERR 22:17:39] R14: 0x0
[LOGERR 22:17:39] R15: 0x7FF4FC8DF760
[LOGERR 22:17:39] RBP: 0x1469FD10
[LOGERR 22:17:39] RSP: 0x1469FC10

**Comment by outryder** [comment]
here is a profile, in case he has already been noticed cheating before:
https://steamcommunity.com/profiles/76561198056434857/

**Comment by outryder** [comment]
host had kinda strange behavior too, and, again, a few seconds after he died, my game crashed.

[LOGERR 22:58:10] ----- [YuiSpy Activated] -----
[LOGERR 22:58:10] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 22:58:10] Exception Flags: 0
[LOGERR 22:58:10] Fault Offset: 0x14082CA64
[LOGERR 22:58:10] Number Parameters: 2
[LOGERR 22:58:10] The instruction at 0x14082CA64 referenced memory at 0xFFFFFFFFFFFFFFFF. The memory could not be read.
[LOGERR 22:58:10] Dumping session information:
[LOGERR 22:58:10] Generating register dump:
[LOGERR 22:58:10] RAX: 0xC22B9348C3EF9219
[LOGERR 22:58:10] RBX: 0x7FF4B0028D30
[LOGERR 22:58:10] RCX: 0x0
[LOGERR 22:58:10] RDX: 0xA71B3B9FFFC37C4
[LOGERR 22:58:10] RDI: 0x7FF4B0028D30
[LOGERR 22:58:10] RSI: 0x0
[LOGERR 22:58:10] R8:  0x0
[LOGERR 22:58:10] R9:  0x7FF49E8552A0
[LOGERR 22:58:10] R10: 0x0
[LOGERR 22:58:10] R11: 0x246
[LOGERR 22:58:10] R12: 0x7FF4AFF3DB80
[LOGERR 22:58:10] R13: 0x0
[LOGERR 22:58:10] R14: 0x0
[LOGERR 22:58:10] R15: 0xAAAAAAAAAAAAAA9
[LOGERR 22:58:10] RBP: 0x7FF49E8552A0
[LOGERR 22:58:10] RSP: 0x3B27FD00

**Comment by outryder** [comment]
Somehow these and the next (3rd) profiles haven't been logged by Watchdog.

**Comment by outryder** [comment]
Last game crash case had nothing suspicious whatsoever. But, still occurred just few seconds after host was killed.

[LOGERR 23:15:10] ----- [YuiSpy Activated] -----
[LOGERR 23:15:10] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 23:15:10] Exception Flags: 0
[LOGERR 23:15:10] Fault Offset: 0x14082CA64
[LOGERR 23:15:10] Number Parameters: 2
[LOGERR 23:15:10] The instruction at 0x14082CA64 referenced memory at 0xFFFFFFFFFFFFFFFF. The memory could not be read.
[LOGERR 23:15:10] Dumping session information:
[LOGERR 23:15:10] Generating register dump:
[LOGERR 23:15:10] RAX: 0x981100007FF4FCE5
[LOGERR 23:15:10] RBX: 0x7FF4FD0527B0
[LOGERR 23:15:10] RCX: 0x0
[LOGERR 23:15:10] RDX: 0xA64955555555555
[LOGERR 23:15:10] RDI: 0x7FF4FD0527B0
[LOGERR 23:15:10] RSI: 0x0
[LOGERR 23:15:10] R8:  0x0
[LOGERR 23:15:10] R9:  0x7FF49E8552A0
[LOGERR 23:15:10] R10: 0x0
[LOGERR 23:15:10] R11: 0x246
[LOGERR 23:15:10] R12: 0x7FF4FCE59032
[LOGERR 23:15:10] R13: 0x0
[LOGERR 23:15:10] R14: 0x0
[LOGERR 23:15:10] R15: 0xAAAAAAAAAAAAAA9
[LOGERR 23:15:10] RBP: 0x7FF49E8552A0
[LOGERR 23:15:10] RSP: 0x31A7FD00

**Comment by outryder** [comment]
@LukeYui 
If you can confirm if it were really malicious instances (especially, 2nd and 3rd cases), please say so.

**Comment by outryder** [comment]
Some additions:

[LOGERR 23:09:47] ----- [YuiSpy Activated] -----
[LOGERR 23:09:47] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 23:09:47] Exception Flags: 0
[LOGERR 23:09:47] Fault Offset: 0x140F06C82
[LOGERR 23:09:47] Number Parameters: 2
[LOGERR 23:09:47] The instruction at 0x140F06C82 referenced memory at 0x0. The memory could not be written.
[LOGERR 23:09:47] Dumping session information:
[LOGERR 23:09:47] Generating register dump:
[LOGERR 23:09:47] RAX: 0x0
[LOGERR 23:09:47] RBX: 0x144643A58
[LOGERR 23:09:47] RCX: 0x2B
[LOGERR 23:09:47] RDX: 0xBC3E46D5
[LOGERR 23:09:47] RDI: 0x0
[LOGERR 23:09:47] RSI: 0x6D5C060
[LOGERR 23:09:47] R8:  0x0
[LOGERR 23:09:47] R9:  0x1
[LOGERR 23:09:47] R10: 0x8000
[LOGERR 23:09:47] R11: 0x9F4FBB0
[LOGERR 23:09:47] R12: 0x7FF41B5916F0
[LOGERR 23:09:47] R13: 0x7FF41B591728
[LOGERR 23:09:47] R14: 0x0
[LOGERR 23:09:47] R15: 0x0
[LOGERR 23:09:47] RBP: 0x0
[LOGERR 23:09:47] RSP: 0x9F4FC98
[LOGERR 23:09:47] ------ [YuiSpy Complete] -----
[LOGERR 23:09:47] ----- [YuiSpy Activated] -----
[LOGERR 23:09:47] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 23:09:47] Exception Flags: 0
[LOGERR 23:09:47] Fault Offset: 0x140F06C82
[LOGERR 23:09:47] Number Parameters: 2
[LOGERR 23:09:47] The instruction at 0x140F06C82 referenced memory at 0x0. The memory could not be written.
[LOGERR 23:09:47] Dumping session information:
[LOGERR 23:09:47] Generating register dump:
[LOGERR 23:09:47] RAX: 0x0
[LOGERR 23:09:47] RBX: 0x144917630
[LOGERR 23:09:47] RCX: 0x2B
[LOGERR 23:09:47] RDX: 0xBC3E46D5
[LOGERR 23:09:47] RDI: 0x7FF41A594710
[LOGERR 23:09:47] RSI: 0x2AFE97C8
[LOGERR 23:09:47] R8:  0x142757068
[LOGERR 23:09:47] R9:  0x40
[LOGERR 23:09:47] R10: 0x240
[LOGERR 23:09:47] R11: 0x351FFB20
[LOGERR 23:09:47] R12: 0x0
[LOGERR 23:09:47] R13: 0x1
[LOGERR 23:09:47] R14: 0x7FF41A594760
[LOGERR 23:09:47] R15: 0x7FF41A5947A0
[LOGERR 23:09:47] RBP: 0x351FFCD0
[LOGERR 23:09:47] RSP: 0x351FFC18
[LOGERR 23:09:47] ------ [YuiSpy Complete] -----

well, Watchdog crashed at regular game exit thru main menu after killing a cheater host.

**Comment by outryder** [comment]
And, well, just in case it may be of use to developers. 
Prior to game/app crash on exit thru menu, there was SL802 stat cheater on SL100 and a host with similar stats. Somehow they took same damage, but host wasn't shown stats cheating.

[LOGERR 03:29:12] ----- [YuiSpy Activated] -----
[LOGERR 03:29:12] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 03:29:12] Exception Flags: 0
[LOGERR 03:29:12] Fault Offset: 0x140F06C82
[LOGERR 03:29:12] Number Parameters: 2
[LOGERR 03:29:12] The instruction at 0x140F06C82 referenced memory at 0x0. The memory could not be written.
[LOGERR 03:29:12] Dumping session information:
[LOGERR 03:29:12] Generating register dump:
[LOGERR 03:29:12] RAX: 0x0
[LOGERR 03:29:12] RBX: 0x144643A58
[LOGERR 03:29:12] RCX: 0x31
[LOGERR 03:29:12] RDX: 0xBDB51B8F
[LOGERR 03:29:12] RDI: 0x0
[LOGERR 03:29:12] RSI: 0x6DCC2C0
[LOGERR 03:29:12] R8:  0x0
[LOGERR 03:29:12] R9:  0x1
[LOGERR 03:29:12] R10: 0x8000
[LOGERR 03:29:12] R11: 0x9F3FBB0
[LOGERR 03:29:12] R12: 0x7FF41B5916F0
[LOGERR 03:29:12] R13: 0x7FF41B591728
[LOGERR 03:29:12] R14: 0x0
[LOGERR 03:29:12] R15: 0x0
[LOGERR 03:29:12] RBP: 0x0
[LOGERR 03:29:12] RSP: 0x9F3FC98
[LOGERR 03:29:12] ------ [YuiSpy Complete] -----
[LOGERR 03:29:13] ----- [YuiSpy Activated] -----
[LOGERR 03:29:13] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 03:29:13] Exception Flags: 0
[LOGERR 03:29:13] Fault Offset: 0x140F06C82
[LOGERR 03:29:13] Number Parameters: 2
[LOGERR 03:29:13] The instruction at 0x140F06C82 referenced memory at 0x0. The memory could not be written.
[LOGERR 03:29:13] Dumping session information:
[LOGERR 03:29:13] Generating register dump:
[LOGERR 03:29:13] RAX: 0x0
[LOGERR 03:29:13] RBX: 0x144917630
[LOGERR 03:29:13] RCX: 0x31
[LOGERR 03:29:13] RDX: 0xBDB51B8F
[LOGERR 03:29:13] RDI: 0x7FF41A594710
[LOGERR 03:29:13] RSI: 0xF67778C8
[LOGERR 03:29:13] R8:  0x142757068
[LOGERR 03:29:13] R9:  0x40
[LOGERR 03:29:13] R10: 0x400
[LOGERR 03:29:13] R11: 0x2C9BFB20
[LOGERR 03:29:13] R12: 0x0
[LOGERR 03:29:13] R13: 0x1
[LOGERR 03:29:13] R14: 0x7FF41A594760
[LOGERR 03:29:13] R15: 0x7FF41A5947A0
[LOGERR 03:29:13] RBP: 0x2C9BFCD0
[LOGERR 03:29:13] RSP: 0x2C9BFC18
[LOGERR 03:29:13] ------ [YuiSpy Complete] -----
