### ISSUE TITLE
Polygon Issues on 1.0.4

### ISSUE THREAD

**Issue by OhhLoz** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#7]
Upon invading (as Aldrich) I got the polygon normal error alongside the disappearance of the overlay. I still believe it was running fine but there was no visual confirmation.

Log File:
[LOGSTR 21:11:02] Launching Dark Souls III...
[LOGSTR 21:11:03] Update Check
[LOGSTR 21:11:03] End Update Check
[LOGSTR 21:11:21] SaveFolderID: 011000010647f566, Savefolder path: C:\Users\Loz\AppData\Roaming\DarkSoulsIII\011000010647f566
[LOGERR 21:11:51] Rendering stack error: B28C9E5F
[LOGERR 21:12:40] Unable to shade polygon normals. Error Code: 6561198065644902 
Inform /u/TheSpicyChef and send your log file.

Also not sure if this is related to the mod, however I got shot with a typical crash crossbow (insane amount of bleed bolts?) and didnt notice any difference from a typical one. Is this mod supposed to reduce the impact of these?

Thanks for your work!

**Comment by Jellybaby34** [comment]
Should be fixed in the new release. Let me know of its not
