### ISSUE TITLE
White screen crash when I tried to equip Dancer's Crown.

### ISSUE THREAD

**Issue by Trilasent** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#71]
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/4770076/DS3PWLog.txt)

Not sure if the location matters but I was in the unlit Firelink Shrine in the Untended Graves when it occurred.

**Comment by LukeYui** [comment]
Hi, sorry for the delay. There is no reason this should have happened, as watchdog does not modify equipment or any offline functions. Has this happened again?

**Comment by Trilasent** [comment]
Not that I can remember. For what it's worth I've made no alterations to my game other than installing Watchdog either.
