### ISSUE TITLE
A few issues when running through Proton [Linux]

### ISSUE THREAD

**Issue by Khrona98** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#74]
Hello there!

It seems there is some issues when using the `PVP Watchdog` on `Linux` through `Steam's Proton`, as some features work correctly, like the save files backup, the sound when opening the game/getting invade/doing invasions and the log file which is created and filled with information, while others like the little HUD/overlay with the stats of players doesn't show up. I also believe F1 to kick also doesn't work, but it requires more testing as it could be that I didn't encounter a hacker yet. I'll update about the kick function here as I test it further.

I'll understand if you can't promise it to work on Linux as it would be one more platform to test and ensure everything works. Yet I thought it would be good to report these issues here, as some of us are playing the game on PC in systems other than Windows.

**Comment by 3JlOy-PYCCKUi** [comment]
I have exactly the same problems, the same HUD does not work. 
It's my system: 
- Manjaro Gnome 20.0.3
- Xanmod LTS kernel (5.4.47-1)
- Nvidia drivers version 440.82
- Proton version is Proton-5.8-GE-2-MF (by GloriousEggroll)

**Comment by ewbteewbte** [comment]
Hey there, same thing on Pop!_OS 20.04. Tho I fixed sound notifications issue with custom path (instruction are in the .ini file). For instance I used some generic .wav files found in libreoffice.
