### ISSUE TITLE
Pressing F1 = CTD: File Included

### ISSUE THREAD

**Issue by QuantumKitten** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#77]
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/4876893/DS3PWLog.txt)

[LOGERR 00:01:24] ----- [YuiSpy Activated] -----
[LOGERR 00:01:24] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 00:01:24] Exception Flags: 0
[LOGERR 00:01:24] Fault Offset: 0x7FFE6359512D
[LOGERR 00:01:24] Number Parameters: 2
[LOGERR 00:01:24] The instruction at 0x7FFE6359512D referenced memory at 0x1. The memory could not be read.
[LOGERR 00:01:24] Dumping session information:
[LOGERR 00:01:24] Player Slot: 1, Name: Turev The Angel, Steam ID: 011000010806E6F5, Owner Steam ID: NULL
[LOGERR 00:01:24] Player Slot: 2, Name: Deputy Doofie, Steam ID: 0110000104FDF45A, Owner Steam ID: 0110000104FDF45A
[LOGERR 00:01:24] Player Slot: 3, Name: Rumtumtugger, Steam ID: 011000010502BDDD, Owner Steam ID: 011000010502BDDD
[LOGERR 00:01:24] Player Slot: 4, Name: Cleber Pernicos, Steam ID: 011000010755016A, Owner Steam ID: 011000010755016A
[LOGERR 00:01:24] Generating register dump:
[LOGERR 00:01:24] RAX: 0xFFFFFFFF
[LOGERR 00:01:24] RBX: 0x7AEF700
[LOGERR 00:01:24] RCX: 0x0
[LOGERR 00:01:24] RDX: 0x1
[LOGERR 00:01:24] RDI: 0x100
[LOGERR 00:01:24] RSI: 0x7AEFC50
[LOGERR 00:01:24] R8:  0x1
[LOGERR 00:01:24] R9:  0x1
[LOGERR 00:01:24] R10: 0x7FFFFFFF
[LOGERR 00:01:24] R11: 0x7AEFC30
[LOGERR 00:01:24] R12: 0x7FFE63570000
[LOGERR 00:01:24] R13: 0x0
[LOGERR 00:01:24] R14: 0x7AEFB68
[LOGERR 00:01:24] R15: 0x7FFE63638030
[LOGERR 00:01:24] RBP: 0x7AEF7A0
[LOGERR 00:01:24] RSP: 0x7AEF578
[LOGERR 00:01:24] ------ [YuiSpy Complete] -----

**Comment by LukeYui** [comment]
Hi, I recommend you use the beta version (1.0.11), as it is fixed here.
