### ISSUE TITLE
Attempting to kick cheaters crashes to desktop

### ISSUE THREAD

**Issue by Sepherence** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#79]
[LOGSTR 01:12:41] Launching Dark Souls III...
[LOGSTR 01:12:41] Fetching data file...
[LOGSTR 01:12:42] Storing data file
[LOGSTR 01:12:42] Opening data file
[LOGSTR 01:12:42] Finished fetching data file
[LOGSTR 01:12:42] Update Check
[LOGSTR 01:12:42] End Update Check
[LOGSTR 01:13:05] SaveFolderID: 0110000103be0dd4, Savefolder path: C:\Users\dflam\AppData\Roaming\DarkSoulsIII\0110000103be0dd4
[LOGERR 01:21:58] Rendering stack error at: 0000000023742649ll
[LOGERR 01:22:00] Rendering stack error at: 0000000023742649ll
[LOGERR 01:24:59] Rendering stack error at: 0000000023742649ll
[LOGERR 01:42:31] Rendering stack error at: 0000000023742649ll
[LOGSTR 10:53:55] Launching Dark Souls III...
[LOGSTR 10:53:55] Fetching data file...
[LOGSTR 10:53:56] Storing data file
[LOGSTR 10:53:56] Opening data file
[LOGSTR 10:53:56] Finished fetching data file
[LOGSTR 10:53:56] Update Check
[LOGSTR 10:53:56] End Update Check
[LOGSTR 10:54:23] SaveFolderID: 0110000103be0dd4, Savefolder path: C:\Users\dflam\AppData\Roaming\DarkSoulsIII\0110000103be0dd4
[LOGSTR 11:39:51] Player: RoBlOxBoY69, SteamID: 011000014264D6B2 is using a family shared account. Main SteamID: 011000010E97C583
[LOGSTR 11:39:51] Player: collmandan, SteamID: 011000014247F233 is using a family shared account. Main SteamID: 0110000115823B26
[LOGSTR 11:49:20] Player: jeretzel051, SteamID: 011000014269488B is using a family shared account. Main SteamID: 0110000107FF76F0
[LOGERR 11:49:25] ----- [YuiSpy Activated] -----
[LOGERR 11:49:25] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 11:49:25] Exception Flags: 0
[LOGERR 11:49:25] Fault Offset: 0x7FF93DE7512D
[LOGERR 11:49:25] Number Parameters: 2
[LOGERR 11:49:25] The instruction at 0x7FF93DE7512D referenced memory at 0x1. The memory could not be read.
[LOGERR 11:49:25] Dumping session information:
[LOGERR 11:49:25] Player Slot: 1, Name: Anastasia, Steam ID: 0110000103BE0DD4, Owner Steam ID: NULL
[LOGERR 11:49:25] Player Slot: 2, Name: Theokoles, Steam ID: 011000014269488B, Owner Steam ID: 0110000107FF76F0
[LOGERR 11:49:25] Generating register dump:
[LOGERR 11:49:25] RAX: 0xFFFFFFFF
[LOGERR 11:49:25] RBX: 0x479F700
[LOGERR 11:49:25] RCX: 0x0
[LOGERR 11:49:25] RDX: 0x1
[LOGERR 11:49:25] RDI: 0x100
[LOGERR 11:49:25] RSI: 0x479FC50
[LOGERR 11:49:25] R8:  0x1
[LOGERR 11:49:25] R9:  0x1
[LOGERR 11:49:25] R10: 0x7FFFFFFF
[LOGERR 11:49:25] R11: 0x479FC30
[LOGERR 11:49:25] R12: 0x7FF93DE50000
[LOGERR 11:49:25] R13: 0x0
[LOGERR 11:49:25] R14: 0x479FB68
[LOGERR 11:49:25] R15: 0x7FF93DF18030
[LOGERR 11:49:25] RBP: 0x479F7A0
[LOGERR 11:49:25] RSP: 0x479F578
[LOGERR 11:49:25] ------ [YuiSpy Complete] -----
[LOGSTR 11:52:01] Launching Dark Souls III...
[LOGSTR 11:52:01] Fetching data file...
[LOGSTR 11:52:02] Update Check
[LOGSTR 11:52:02] Storing data file
[LOGSTR 11:52:02] Opening data file
[LOGSTR 11:52:02] Finished fetching data file
[LOGSTR 11:52:25] SaveFolderID: 0110000103be0dd4, Savefolder path: C:\Users\dflam\AppData\Roaming\DarkSoulsIII\0110000103be0dd4
[LOGSTR 11:54:32] Player: jeretzel051, SteamID: 011000014269488B is using a family shared account. Main SteamID: 0110000107FF76F0
[LOGERR 11:54:46] ----- [YuiSpy Activated] -----
[LOGERR 11:54:46] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 11:54:46] Exception Flags: 0
[LOGERR 11:54:46] Fault Offset: 0x7FF93DE7512D
[LOGERR 11:54:46] Number Parameters: 2
[LOGERR 11:54:46] The instruction at 0x7FF93DE7512D referenced memory at 0x1. The memory could not be read.
[LOGERR 11:54:46] Dumping session information:
[LOGERR 11:54:46] Player Slot: 1, Name: Anastasia, Steam ID: 0110000103BE0DD4, Owner Steam ID: NULL
[LOGERR 11:54:46] Player Slot: 2, Name: Theokoles, Steam ID: 011000014269488B, Owner Steam ID: 0110000107FF76F0
[LOGERR 11:54:46] Generating register dump:
[LOGERR 11:54:46] RAX: 0xFFFFFFFF
[LOGERR 11:54:46] RBX: 0x7C3F700
[LOGERR 11:54:46] RCX: 0x0
[LOGERR 11:54:46] RDX: 0x1
[LOGERR 11:54:46] RDI: 0x100
[LOGERR 11:54:46] RSI: 0x7C3FC50
[LOGERR 11:54:46] R8:  0x1
[LOGERR 11:54:46] R9:  0x1
[LOGERR 11:54:46] R10: 0x7FFFFFFF
[LOGERR 11:54:46] R11: 0x7C3FC30
[LOGERR 11:54:46] R12: 0x7FF93DE50000
[LOGERR 11:54:46] R13: 0x0
[LOGERR 11:54:46] R14: 0x7C3FB68
[LOGERR 11:54:46] R15: 0x7FF93DF18030
[LOGERR 11:54:46] RBP: 0x7C3F7A0
[LOGERR 11:54:46] RSP: 0x7C3F578
[LOGERR 11:54:46] ------ [YuiSpy Complete] -----

**Comment by LukeYui** [comment]
Sorry for the delay. This is fixed in the beta (1.0.11), I recommend you use this.
