### ISSUE TITLE
Crash when invading 

### ISSUE THREAD

**Issue by vodboi** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#80]
Got a crash when invading someone outside Pontiff's, here's the crash info:

[LOGERR 06:50:02] ----- [YuiSpy Activated] -----
[LOGERR 06:50:02] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 06:50:02] Exception Flags: 0
[LOGERR 06:50:02] Fault Offset: 0x7FEF5854B77
[LOGERR 06:50:02] Number Parameters: 2
[LOGERR 06:50:02] d3d11.dll+14B77
[LOGERR 06:50:02] The instruction at 0x7FEF5854B77 referenced memory at 0x80. The memory could not be read.
[LOGERR 06:50:02] Dumping session information:
[LOGERR 06:50:02] Player Slot: 1, Name: Artorias, Steam ID: 01100001051703D1, Owner Steam ID: NULL
[LOGERR 06:50:03] Player Slot: 2, Name: BIG HURT, Steam ID: 011000013DCF8891, Owner Steam ID: 011000010B5BEA6C
[LOGERR 06:50:03] Player Slot: 3, Name: Moonmy, Steam ID: 011000013CBDC864, Owner Steam ID: 011000013CBDC864
[LOGERR 06:50:03] Player Slot: 4, Name: long, Steam ID: 011000013C057A8E, Owner Steam ID: 011000013C057A8E
[LOGERR 06:50:03] Generating register dump:
[LOGERR 06:50:03] RAX: 0x0
[LOGERR 06:50:03] RBX: 0x0
[LOGERR 06:50:03] RCX: 0x7FEF58876F0
[LOGERR 06:50:03] RDX: 0x0
[LOGERR 06:50:03] RDI: 0x7FEF5887410
[LOGERR 06:50:03] RSI: 0x7FEF58874F0
[LOGERR 06:50:03] R8:  0x7FFA09A39D0
[LOGERR 06:50:03] R9:  0x7FEEEA20000
[LOGERR 06:50:03] R10: 0x2B87E30
[LOGERR 06:50:03] R11: 0x72AF710
[LOGERR 06:50:03] R12: 0x2
[LOGERR 06:50:03] R13: 0x4
[LOGERR 06:50:03] R14: 0x2
[LOGERR 06:50:03] R15: 0x4
[LOGERR 06:50:03] RBP: 0x72AF820
[LOGERR 06:50:03] RSP: 0x72AF720
[LOGERR 06:50:03] ------ [YuiSpy Complete] -----

**Comment by LukeYui** [comment]
Sorry for the delay. This should be fixed in the beta.
