### ISSUE TITLE
Randomly Crashed

### ISSUE THREAD

**Issue by kesmese152** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#81]
I think i was invaded after dragonslayer armour because i just heard the error sound and everything went white here is the log :

[LOGERR 19:50:51] ----- [YuiSpy Activated] -----
[LOGERR 19:50:51] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 19:50:51] Exception Flags: 0
[LOGERR 19:50:51] Fault Offset: 0x1401AF73D
[LOGERR 19:50:51] Number Parameters: 2
[LOGERR 19:50:51] The instruction at 0x1401AF73D referenced memory at 0x518. The memory could not be read.
[LOGERR 19:50:51] Dumping session information:
[LOGERR 19:50:51] Generating register dump:
[LOGERR 19:50:51] RAX: 0xA0060F
[LOGERR 19:50:51] RBX: 0x0
[LOGERR 19:50:51] RCX: 0xA0060F8B
[LOGERR 19:50:51] RDX: 0x8B
[LOGERR 19:50:51] RDI: 0x7ACA5CA7
[LOGERR 19:50:51] RSI: 0x62D7468
[LOGERR 19:50:51] R8:  0x62D7580
[LOGERR 19:50:51] R9:  0x62D7580
[LOGERR 19:50:51] R10: 0x508
[LOGERR 19:50:51] R11: 0x144714CF0
[LOGERR 19:50:51] R12: 0x7FF49E3D4218
[LOGERR 19:50:51] R13: 0x0
[LOGERR 19:50:51] R14: 0x118
[LOGERR 19:50:51] R15: 0xA
[LOGERR 19:50:51] RBP: 0x62D7468
[LOGERR 19:50:51] RSP: 0x6FAE880
[LOGERR 19:50:51] ------ [YuiSpy Complete] -----

**Comment by kesmese152** [comment]
Crashed once more while i was invading :

[LOGERR 15:10:17] ----- [YuiSpy Activated] -----
[LOGERR 15:10:17] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 15:10:17] Exception Flags: 0
[LOGERR 15:10:17] Fault Offset: 0x14006483E
[LOGERR 15:10:17] Number Parameters: 2
[LOGERR 15:10:17] The instruction at 0x14006483E referenced memory at 0x0. The memory could not be read.
[LOGERR 15:10:17] Dumping session information:
[LOGERR 15:10:17] Player Slot: 1, Name: Kuhaku, Steam ID: 0110000109B97AAA, Owner Steam ID: NULL
[LOGERR 15:10:17] Player Slot: 2, Name: ming, Steam ID: 0110000134B1A0C8, Owner Steam ID: 0110000134B1A0C8
[LOGERR 15:10:17] Generating register dump:
[LOGERR 15:10:17] RAX: 0x0
[LOGERR 15:10:17] RBX: 0x0
[LOGERR 15:10:17] RCX: 0x0
[LOGERR 15:10:18] RDX: 0x0
[LOGERR 15:10:18] RDI: 0x7FF438600890
[LOGERR 15:10:18] RSI: 0x1304ED60
[LOGERR 15:10:18] R8:  0x1447258B8
[LOGERR 15:10:18] R9:  0x1
[LOGERR 15:10:18] R10: 0x7FF43798C600
[LOGERR 15:10:18] R11: 0x0
[LOGERR 15:10:18] R12: 0x7FF42F180E40
[LOGERR 15:10:18] R13: 0x7FF43798B560
[LOGERR 15:10:18] R14: 0x7FF43368A450
[LOGERR 15:10:18] R15: 0x7FF43798AA78
[LOGERR 15:10:18] RBP: 0x1304EAD1
[LOGERR 15:10:18] RSP: 0x1304EA10
[LOGERR 15:10:18] ------ [YuiSpy Complete] -----
[LOGERR 15:10:18] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 15:10:18] Exception Flags: 0
[LOGERR 15:10:18] Fault Offset: 0x14006483E
[LOGERR 15:10:18] Number Parameters: 2
[LOGERR 15:10:18] The instruction at 0x14006483E referenced memory at 0x0. The memory could not be read.
[LOGERR 15:10:18] Dumping session information:
[LOGERR 15:10:18] Player Slot: 1, Name: Kuhaku, Steam ID: 0110000109B97AAA, Owner Steam ID: NULL
[LOGERR 15:10:18] Player Slot: 2, Name: ming, Steam ID: 0110000134B1A0C8, Owner Steam ID: 0110000134B1A0C8
[LOGERR 15:10:18] Generating register dump:
[LOGERR 15:10:18] RAX: 0x0
[LOGERR 15:10:18] RBX: 0x0
[LOGERR 15:10:18] RCX: 0x0
[LOGERR 15:10:18] RDX: 0x0
[LOGERR 15:10:18] RDI: 0x7FF4358AD010
[LOGERR 15:10:18] RSI: 0x1324ED60
[LOGERR 15:10:18] R8:  0x1447258B8
[LOGERR 15:10:18] R9:  0x1
[LOGERR 15:10:18] R10: 0x7FF43066A820
[LOGERR 15:10:18] R11: 0x0
[LOGERR 15:10:18] R12: 0x7FF42F189A80
[LOGERR 15:10:18] R13: 0x7FF430E460D0
[LOGERR 15:10:18] R14: 0x7FF4336890C0
[LOGERR 15:10:18] R15: 0x7FF430A0CA48
[LOGERR 15:10:18] RBP: 0x1324EAD1
[LOGERR 15:10:18] RSP: 0x1324EA10
[LOGERR 15:10:18] ------ [YuiSpy Complete] -----

**Comment by LukeYui** [comment]
Hi, are you using the beta version (1.0.11)?

**Comment by kesmese152** [comment]
No i was using 1.0.10 version and just saw there is a newer version so will download that one now.

**Comment by LukeYui** [comment]
OK, thanks for getting back to me. Are you also using any other mods? (Graphics mods, wex dust, etc.)

**Comment by kesmese152** [comment]
When it happened i was only using watchdog mod nothing else tho now i am also using wex dust but didnt get crashes after that it just happened twice.

**Comment by kesmese152** [comment]
Didn't happen at all after those 2 crashes when i wasnt using any other mod or after using wex dust and still didnt crash with new update will create a new issue if it does.
