### ISSUE TITLE
Windows notification sound every time i invade

### ISSUE THREAD

**Issue by smooshybutepic** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#82]
So every time i invade or somebody gets summoned the windows notification sound plays. its kind of annoying is there some way to fix it?? thanks

**Comment by LukeYui** [comment]
Yes, go into the options file (DS3PWSettings.ini) and change:

`InvasionNotification = true`

to 

`InvasionNotification = false`

**Comment by smooshybutepic** [comment]
> Yes, go into the options file (DS3PWSettings.ini) and change:
> 
> `InvasionNotification = true`
> 
> to
> 
> `InvasionNotification = false`

thanks a lot
