### ISSUE TITLE
Kicking Flagged User Crashes

### ISSUE THREAD

**Issue by clstr** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#83]
Version: 1.0.10
I am also running Wex Dust, nothing else.

[LOGERR 02:54:58] ----- [YuiSpy Activated] -----
[LOGERR 02:54:58] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 02:54:58] Exception Flags: 0
[LOGERR 02:54:58] Fault Offset: 0x7FF8773A512D
[LOGERR 02:54:58] Number Parameters: 2
[LOGERR 02:54:58] The instruction at 0x7FF8773A512D referenced memory at 0x1. The memory could not be read.
[LOGERR 02:54:58] Dumping session information:
[LOGERR 02:54:58] Player Slot: 1, Name: Anna, Steam ID: 0110000104665745, Owner Steam ID: NULL
[LOGERR 02:54:58] Player Slot: 2, Name: unbroken Fahad, Steam ID: 011000010B55BB58, Owner Steam ID: 011000010B55BB58
[LOGERR 02:54:58] Generating register dump:
[LOGERR 02:54:58] RAX: 0xFFFFFFFF
[LOGERR 02:54:58] RBX: 0x481F700
[LOGERR 02:54:58] RCX: 0x0
[LOGERR 02:54:58] RDX: 0x1
[LOGERR 02:54:58] RDI: 0x100
[LOGERR 02:54:58] RSI: 0x481FC50
[LOGERR 02:54:58] R8:  0x1
[LOGERR 02:54:58] R9:  0x1
[LOGERR 02:54:58] R10: 0x7FFFFFFF
[LOGERR 02:54:58] R11: 0x481FC30
[LOGERR 02:54:58] R12: 0x7FF877380000
[LOGERR 02:54:58] R13: 0x0
[LOGERR 02:54:58] R14: 0x481FB68
[LOGERR 02:54:58] R15: 0x7FF877448030
[LOGERR 02:54:58] RBP: 0x481F7A0
[LOGERR 02:54:58] RSP: 0x481F578
[LOGERR 02:54:58] ------ [YuiSpy Complete] -----

**Comment by mbartnic** [comment]
Game crashed when kicking blue phantom - Jesus Christ - invalid stats

[LOGSTR 01:10:03] Player: [REDACTED-GDPR], SteamID: [REDACTED-GDPR] is using a family shared account. Main SteamID: [REDACTED-GDPR]
[LOGERR 01:10:14] ----- [YuiSpy Activated] -----
[LOGERR 01:10:14] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 01:10:14] Exception Flags: 0
[LOGERR 01:10:14] Fault Offset: 0x7FFFC7DE5170
[LOGERR 01:10:14] Number Parameters: 2
[LOGERR 01:10:14] The instruction at 0x7FFFC7DE5170 referenced memory at 0x2. The memory could not be read.
[LOGERR 01:10:14] Dumping session information:
[LOGERR 01:10:14] Player Slot: 1, Name: Edith, Steam ID: [REDACTED-GDPR], Owner Steam ID: NULL
[LOGERR 01:10:14] Player Slot: 2, Name: Loyal Lapp, Steam ID: [REDACTED-GDPR], Owner Steam ID: [REDACTED-GDPR]
[LOGERR 01:10:14] Player Slot: 3, Name: Jesus Christ, Steam ID: [REDACTED-GDPR], Owner Steam ID: [REDACTED-GDPR]
[LOGERR 01:10:14] Generating register dump:
[LOGERR 01:10:14] RAX: 0x20
[LOGERR 01:10:14] RBX: 0x473F700
[LOGERR 01:10:14] RCX: 0x0
[LOGERR 01:10:14] RDX: 0x2
[LOGERR 01:10:14] RDI: 0x100
[LOGERR 01:10:14] RSI: 0x473FC50
[LOGERR 01:10:14] R8:  0x2
[LOGERR 01:10:14] R9:  0x2
[LOGERR 01:10:14] R10: 0x7FFFFFFF
[LOGERR 01:10:14] R11: 0xF
[LOGERR 01:10:14] R12: 0x7FFFC7DC0000
[LOGERR 01:10:14] R13: 0x0
[LOGERR 01:10:14] R14: 0x473FB68
[LOGERR 01:10:14] R15: 0x7FFFC7E88030
[LOGERR 01:10:14] RBP: 0x473F7A0
[LOGERR 01:10:14] RSP: 0x473F578
[LOGERR 01:10:14] ------ [YuiSpy Complete] -----
