### ISSUE TITLE
CTD on startup, using 1.0.11

### ISSUE THREAD

**Issue by xPlodEEE** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#85]
Using only PVP Watchdog
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/5135292/DS3PWLog.txt)

**Comment by RandomUser99** [comment]
@xPlodEEE If you get the crash on startup after downloading the mod from Nexus mods, download direct from this repository and try again. Fixed it for me.
