### ISSUE TITLE
Crash on Start-Up. 1.0.11

### ISSUE THREAD

**Issue by KingThe100Ton** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#87]
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/5177880/DS3PWLog.txt)

**Comment by then4p** [comment]
I'm having crashes too. Especially when I die/the game loads another area.

[DS3PWLog1234.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/5250458/DS3PWLog1234.txt)
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/5250459/DS3PWLog.txt)
[DS3PWLog19_05.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/5250460/DS3PWLog19_05.txt)
[DS3PWLog20_03.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/5250461/DS3PWLog20_03.txt)

**Comment by RandomUser99** [comment]
@KingThe100Ton @then4p  If you get the crash on startup after downloading the mod from Nexus mods, download direct from this repository and try again. Fixed it for me.

**Comment by LazySoda** [comment]
> 
> 
> @KingThe100Ton @then4p If you get the crash on startup after downloading the mod from Nexus mods, download direct from this repository and try again. Fixed it for me.

I came here after getting the same issue, so I tried downloading it directly from here like you said, but I'm still getting the memory writing crash.

> [LOGERR 16:37:58] ----- [YuiSpy Activated] -----
[LOGERR 16:37:58] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 16:37:58] Exception Flags: 0
[LOGERR 16:37:58] Fault Offset: 0x7FF9D57F0000
[LOGERR 16:37:58] Number Parameters: 2
[LOGERR 16:37:58] The instruction at 0x7FF9D57F0000 referenced memory at 0x7FF9D57F0000. The memory could not be written.
[LOGERR 16:37:58] Dumping session information:
[LOGERR 16:37:58] Generating register dump:
[LOGERR 16:37:58] RAX: 0x7FF98AD1B438
[LOGERR 16:37:58] RBX: 0x7FF42EF0BFB0
[LOGERR 16:37:58] RCX: 0xB304EB0
[LOGERR 16:37:58] RDX: 0x1
[LOGERR 16:37:58] RDI: 0x7FF42F171C40
[LOGERR 16:37:58] RSI: 0x1
[LOGERR 16:37:58] R8:  0x0
[LOGERR 16:37:58] R9:  0x8B60E578
[LOGERR 16:37:58] R10: 0x14EFA0
[LOGERR 16:37:58] R11: 0x8B60E5B8
[LOGERR 16:37:58] R12: 0x0
[LOGERR 16:37:58] R13: 0x7FF49DEA50E0
[LOGERR 16:37:58] R14: 0x1
