### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HaloSam296** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#88]
Crash Log:

[LOGSTR 19:30:58] Launching Dark Souls III...
[LOGSTR 19:30:58] Fetching data file...
[LOGERR 19:30:58] ----- [YuiSpy Activated] -----
[LOGERR 19:30:58] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 19:30:58] Exception Flags: 0
[LOGERR 19:30:58] Fault Offset: 0x0
[LOGERR 19:30:58] Number Parameters: 2
[LOGERR 19:30:58] The instruction at 0x0 referenced memory at 0x0. The memory could not be written.
[LOGERR 19:30:58] Dumping session information:
[LOGERR 19:30:58] Generating register dump:
[LOGERR 19:30:58] RAX: 0x4641DA0
[LOGERR 19:30:58] RBX: 0x601
[LOGERR 19:30:58] RCX: 0x590
[LOGERR 19:30:58] RDX: 0x4641D90
[LOGERR 19:30:58] RDI: 0x4641C40
[LOGERR 19:30:58] RSI: 0x4607178
[LOGERR 19:30:58] R8:  0x1
[LOGERR 19:30:58] R9:  0x23EF6F8
[LOGERR 19:30:58] R10: 0x50
[LOGERR 19:30:58] R11: 0x246
[LOGERR 19:30:58] R12: 0x0
[LOGERR 19:30:58] R13: 0x0
[LOGERR 19:30:58] R14: 0x4641C50
[LOGERR 19:30:58] R15: 0xFFFFFFFFFFFFFFFF
[LOGERR 19:30:58] RBP: 0x23EF719
[LOGERR 19:30:58] RSP: 0x23EF658
[LOGERR 19:30:58] ------ [YuiSpy Complete] -----
[LOGSTR 19:30:58] Storing data file
[LOGSTR 19:30:58] Opening data file
[LOGSTR 19:30:58] Finished fetching data file
[LOGSTR 19:31:14] SaveFolderID: 011000010dbb3703, Savefolder path: C:\Users\samma\AppData\Roaming\DarkSoulsIII\011000010dbb3703
[LOGSTR 19:33:32] Launching Dark Souls III...
[LOGSTR 19:33:32] Fetching data file...
[LOGERR 19:33:32] ----- [YuiSpy Activated] -----
[LOGERR 19:33:32] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 19:33:32] Exception Flags: 0
[LOGERR 19:33:32] Fault Offset: 0x0
[LOGERR 19:33:32] Number Parameters: 2
[LOGERR 19:33:32] The instruction at 0x0 referenced memory at 0x0. The memory could not be written.
[LOGERR 19:33:32] Dumping session information:
[LOGERR 19:33:32] Generating register dump:
[LOGERR 19:33:32] RAX: 0x48C5A70
[LOGERR 19:33:32] RBX: 0x601
[LOGERR 19:33:32] RCX: 0x5BC
[LOGERR 19:33:32] RDX: 0x48C5A60
[LOGERR 19:33:32] RDI: 0x48C5910
[LOGERR 19:33:32] RSI: 0x487C918
[LOGERR 19:33:32] R8:  0x1
[LOGERR 19:33:32] R9:  0x86BF6F8
[LOGERR 19:33:32] R10: 0x50
[LOGERR 19:33:32] R11: 0x246
[LOGERR 19:33:32] R12: 0x0
[LOGERR 19:33:32] R13: 0x0
[LOGERR 19:33:32] R14: 0x48C5920
[LOGERR 19:33:32] R15: 0xFFFFFFFFFFFFFFFF
[LOGERR 19:33:32] RBP: 0x86BF719
[LOGERR 19:33:32] RSP: 0x86BF658
[LOGERR 19:33:32] ------ [YuiSpy Complete] -----
[LOGSTR 19:33:32] Update Check
[LOGSTR 19:33:32] End Update Check
[LOGERR 19:33:42] ----- [YuiSpy Activated] -----
[LOGERR 19:33:42] Exception Code: 0xC0000005 (ACCESS VIOLATION)
[LOGERR 19:33:42] Exception Flags: 0
[LOGERR 19:33:42] Fault Offset: 0x7FFA71D6BF53
[LOGERR 19:33:42] Number Parameters: 2
[LOGERR 19:33:42] d3d11.dll+1BF53
[LOGERR 19:33:42] The instruction at 0x7FFA71D6BF53 referenced memory at 0x40. The memory could not be read.
[LOGERR 19:33:42] Dumping session information:
[LOGERR 19:33:42] Generating register dump:
[LOGERR 19:33:42] RAX: 0x0
[LOGERR 19:33:42] RBX: 0x7FFE0385
[LOGERR 19:33:42] RCX: 0x7FFA72700000
[LOGERR 19:33:42] RDX: 0x0
[LOGERR 19:33:42] RDI: 0x0
[LOGERR 19:33:42] RSI: 0x1
[LOGERR 19:33:42] R8:  0x1
[LOGERR 19:33:42] R9:  0x7FFA78C3FAD0
[LOGERR 19:33:42] R10: 0x7FFE0384
[LOGERR 19:33:42] R11: 0x86BE050
[LOGERR 19:33:42] R12: 0x7FFA71D7BEDC
[LOGERR 19:33:42] R13: 0x86BE710
[LOGERR 19:33:42] R14: 0x7FFA71D50000
[LOGERR 19:33:42] R15: 0x1
[LOGERR 19:33:42] RBP: 0x86BE250
[LOGERR 19:33:42] RSP: 0x86BDF70
[LOGERR 19:33:42] ------ [YuiSpy Complete] -----

**Comment by RandomUser99** [comment]
@HaloSam296 If you get the crash on startup after downloading the mod from Nexus mods, download direct from this repository and try again. Fixed it for me.
