### ISSUE TITLE
List player stats?

### ISSUE THREAD

**Issue by OhhLoz** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#9]
Hi,

Perhaps this strays away from the mods original purpose as an anti cheat tool, but maybe having an option to list player stats next to their names similarly to how they are listed when a cheater is present would be beneficial.

Or this is giving people who use this tool an unfair advantage? I am aware alot of people use cheat engine to see recent players, current players and detect stat anomalies much like this mod.

Thank you,
Loz

**Comment by LukeYui** [comment]
Thanks for the question, I don't think it would give a massive advantage, but it also might be a bit too much information on-screen at once and the display would become a bit too crowded.

Watchdog also primarily exists to protect people from cheaters, so for these reasons I don't think it would be worth adding.

**Comment by cridus** [comment]
The original DSPW for DS1 initially showed the stats of other players and after a lot of people complained, this behavior was changed. So I guess it shouldn't be re-introduced.

**Comment by Jellybaby34** [comment]
This won't be happening. It gives you an advantage in terms of estimating build features such as equipment weight, health, ability to use spells etc.
