### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by frostcirno** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#94]
when I die/the game loads another area.
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/5904814/DS3PWLog.txt)

**Comment by PHD-Chaos** [comment]
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/5939259/DS3PWLog.txt)

Game crashes just after invader loads in. Was in the same spot in the settlement when it happened twice in a row.
